# Generated by Django 3.2.8 on 2021-11-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_row', models.SmallIntegerField()),
                ('seat_type', models.SmallIntegerField()),
                ('seat_no', models.CharField(max_length=5)),
                ('seat_section', models.CharField(max_length=1)),
                ('hall_no', models.SmallIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('hall_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.seatmatrix')),
                ('title', models.ManyToManyField(related_name='movieshows', to='movie.MovieDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('halls', models.ManyToManyField(related_name='theatre', to='show.ShowDetail')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
