# Generated by Django 3.2.8 on 2021-10-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.PositiveIntegerField()),
                ('mname', models.CharField(max_length=20)),
                ('mgenre', models.CharField(max_length=20)),
                ('mrating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('budget', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.PositiveIntegerField()),
                ('tname', models.CharField(max_length=20)),
                ('halls', models.SmallIntegerField()),
                ('taddress', models.CharField(max_length=30)),
                ('tphone', models.BigIntegerField()),
                ('trating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='show_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.PositiveIntegerField()),
                ('running_time', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('hall_no', models.SmallIntegerField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.movie_detail')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.theatre')),
            ],
        ),
    ]
