# Generated by Django 3.2.8 on 2021-10-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relational_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_detail',
            name='running_time',
            field=models.DurationField(),
        ),
        migrations.CreateModel(
            name='seat_matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.PositiveIntegerField()),
                ('seat_row', models.SmallIntegerField()),
                ('seat_type', models.SmallIntegerField()),
                ('seat_no', models.CharField(max_length=5)),
                ('seat_section', models.CharField(max_length=1)),
                ('hall_no', models.SmallIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.theatre')),
            ],
        ),
    ]
