# Generated by Django 3.2.8 on 2021-10-31 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relational_table', '0002_auto_20211101_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_type', models.SmallIntegerField()),
                ('rate', models.SmallIntegerField()),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.show_detail')),
            ],
        ),
    ]
