# Generated by Django 3.2.8 on 2021-10-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relational_table', '0003_ticket_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgid', models.PositiveIntegerField()),
                ('mpassword', models.CharField(max_length=10)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.theatre')),
            ],
        ),
    ]
