# Generated by Django 3.2.8 on 2021-10-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relational_table', '0004_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=30)),
                ('contact', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
