# Generated by Django 3.2.8 on 2021-10-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relational_table', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField()),
                ('booking_time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.customer')),
                ('mgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.manager')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.ticket_offer')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.seat_matrix')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.show_detail')),
            ],
        ),
    ]
