# Generated by Django 3.2.8 on 2021-10-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relational_table', '0006_booked_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.PositiveBigIntegerField()),
                ('transaction_status', models.CharField(max_length=10)),
                ('booking_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.customer')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_table.booked_seat')),
            ],
        ),
    ]
