# Generated by Django 3.2.9 on 2021-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('director', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=20)),
                ('cast', models.ManyToManyField(related_name='movies', to='movie.MovieCast')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
