# Generated by Django 3.2.9 on 2021-11-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20211109_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
