# Generated by Django 3.2.9 on 2021-11-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20211110_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='about',
            field=models.CharField(default='Super duper hit movie :)', max_length=1000),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='movie_cover'),
        ),
    ]
